<?php
  date_default_timezone_set('America/Mexico_City');
  include_once("clase_usuario.php");
  include_once('clase_log.php');
  $usuario= NEW Usuario($_POST['id']);
  $logs = NEW Log(0);
  $usuario->editar_usuario($_POST['id'],urldecode($_POST['usuario']),$_POST['nivel'],urldecode($_POST['nombre_completo']),urldecode($_POST['puesto']),urldecode($_POST['celular']),urldecode($_POST['correo']),urldecode($_POST['direccion']),$_POST['usuario_ver'],$_POST['usuario_agregar'],$_POST['usuario_editar'],$_POST['usuario_borrar'],$_POST['cliente_ver'],$_POST['cliente_agregar'],$_POST['cliente_editar'],$_POST['cliente_borrar'],$_POST['inventario_ver'],$_POST['inventario_agregar'],$_POST['inventario_editar'],$_POST['inventario_borrar'],$_POST['requisicion_ver'],$_POST['requisicion_agregar'],$_POST['requisicion_editar'],$_POST['requisicion_borrar'],$_POST['salida_ver'],$_POST['salida_agregar'],$_POST['salida_editar'],$_POST['salida_borrar'],$_POST['salida_aprobar'],$_POST['regreso_ver'],$_POST['regreso_agregar'],$_POST['regreso_editar'],$_POST['regreso_borrar'],$_POST['necesidades_ver'],$_POST['necesidades_agregar'],$_POST['necesidades_editar'],$_POST['necesidades_borrar'],$_POST['cotizaciones_ver'],$_POST['cotizaciones_agregar'],$_POST['cotizaciones_editar'],$_POST['cotizaciones_borrar'],$_POST['servicio_ver'],$_POST['desperdicio_entrada_ver'],$_POST['desperdicio_entrada_agregar'],$_POST['desperdicio_entrada_editar'],$_POST['desperdicio_entrada_borrar'],$_POST['desperdicio_salida_ver'],$_POST['desperdicio_salida_agregar'],$_POST['desperdicio_salida_editar'],$_POST['desperdicio_salida_borrar'],$_POST['logs_ver'],$_POST['proveedor_ver'],$_POST['proveedor_agregar'],$_POST['proveedor_editar'],$_POST['proveedor_borrar'],$_POST['herramienta_ver'],$_POST['herramienta_agregar'],$_POST['herramienta_editar'],$_POST['herramienta_borrar'],$_POST['servicio_login'],$_POST['factura_ver'],$_POST['factura_agregar'],$_POST['factura_editar'],$_POST['factura_borrar'],$_POST['orden_ver'],$_POST['orden_agregar'],$_POST['orden_editar'],$_POST['orden_borrar']);
  $logs->guardar_log($_POST['usuario_id'],"Editar usuario: ". $_POST['id']);
?>
